### ISSUE TITLE
place selection failed :error

### ISSUE THREAD

**Issue by sagaleaditya** [thesabareesh/protrip#6]
when clicked on searched bar error appears

**Comment by lizwikagiso** [comment]
Did you manage tp sort the error?

**Comment by kofimokome** [comment]
I have the same error
Can some help me?

**Comment by burhanwork** [comment]
i have same error too

**Comment by thesabareesh** [comment]
Please refer to google location api to get your api key.
https://developers.google.com/maps/documentation/geolocation/get-api-key
