### ISSUE TITLE
Placelist Activity shows blank list with Imaageview at Top

### ISSUE THREAD

**Issue by BlueYeti1881** [thesabareesh/protrip#7]
![40390780_843811072490425_4596954117393350656_n](https://user-images.githubusercontent.com/30164271/44810472-80224e00-abf1-11e8-8a25-4a9757b69a2c.png)
![40392893_1204303276393841_1670669590117482496_n](https://user-images.githubusercontent.com/30164271/44810473-80224e00-abf1-11e8-91e8-3c64a54fb89e.png)
![40492194_565617463854496_3125387537397317632_n](https://user-images.githubusercontent.com/30164271/44810474-80224e00-abf1-11e8-9bd5-5981772ae523.png)

Hlo Sir, 

I was able to sucessfully build the app and run.when opened it shows me  the search bar and when searched any city and clicked on it shows me  with Hotels, Resturants  and other two option fragment..but then if I clicked in any of them ..it shows no  any list oa availaible hotels or Resturants.  there is imageview  at top which contain related image of searched place ..but list is empty and shows white background..please help.

**Comment by saurav9005** [comment]
@BlueYeti1881 did you solved that problem. Let me know, I am also facing the same problem.

Thanks

**Comment by thesabareesh** [comment]
Please refer to google location api to get your api key.
https://developers.google.com/maps/documentation/geolocation/get-api-key
